### ISSUE TITLE
New person problem

### ISSUE THREAD

**Issue by ndbnimbus** [UoE-macOS/autopkg-recipes#11]
Could not find parent recipe for com.github.andrewvalentine.munki.native-instruments.product

I keep getting this when trying to run the Native Instruments ones.
I am fairly new to autopkg, so excuse my ignorance if this is super simple..

**Comment by ndbnimbus** [comment]
Figured it out!

**Comment by geoffklee** [comment]
Great! Just shout if I can help with anything.
